# Generated by Django 5.0.1 on 2024-02-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0003_feedback_delete_contactus'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='Feedback',
        ),
    ]
