# Generated by Django 5.0.1 on 2024-02-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0004_alter_feedback_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.AlterField(
            model_name='register',
            name='phonenumber',
            field=models.PositiveBigIntegerField(),
        ),
    ]
