# Generated by Django 5.0.1 on 2024-02-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0005_delete_feedback_alter_register_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phonenumber', models.CharField(max_length=100)),
                ('feedback_txt', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
