# Generated by Django 5.0.1 on 2024-02-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0006_feedback'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='Feedback',
        ),
    ]
