# Generated by Django 5.0.1 on 2024-02-14 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0007_alter_feedback_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='FeedbackForm',
        ),
    ]
