# Generated by Django 5.0.1 on 2024-02-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0008_alter_feedback_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_txt',
            field=models.TextField(max_length=100),
        ),
    ]
