# Generated by Django 5.0.1 on 2024-02-14 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0009_alter_feedback_feedback_txt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_txt',
            new_name='feedback_text',
        ),
    ]
