# Generated by Django 5.0.1 on 2024-02-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0010_rename_feedback_txt_feedback_feedback_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phonenumber',
            field=models.PositiveBigIntegerField(),
        ),
    ]
